// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVnK1YTY-nMv239ZYNyzIYfN-Hh2HG84w',
    appId: '1:1080681105639:web:589c8589a566e58085fa42',
    messagingSenderId: '1080681105639',
    projectId: 'cattlecare',
    authDomain: 'cattlecare.firebaseapp.com',
    storageBucket: 'cattlecare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbdULoD6J0ra888WTLd5RI7BEsrhFA-i4',
    appId: '1:1080681105639:android:7aae14cc9baf685985fa42',
    messagingSenderId: '1080681105639',
    projectId: 'cattlecare',
    storageBucket: 'cattlecare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hCOV2OfxcpCgMBmNDRwYIBV551uAURI',
    appId: '1:1080681105639:ios:feaf4e7eb60b18f885fa42',
    messagingSenderId: '1080681105639',
    projectId: 'cattlecare',
    storageBucket: 'cattlecare.appspot.com',
    iosClientId: '1080681105639-5ntnn4a9lfk04al2pagh6u5la71kpmk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-hCOV2OfxcpCgMBmNDRwYIBV551uAURI',
    appId: '1:1080681105639:ios:feaf4e7eb60b18f885fa42',
    messagingSenderId: '1080681105639',
    projectId: 'cattlecare',
    storageBucket: 'cattlecare.appspot.com',
    iosClientId: '1080681105639-5ntnn4a9lfk04al2pagh6u5la71kpmk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleCare',
  );
}
